### ISSUE TITLE
Redfish commands for service-config-manager

### ISSUE THREAD

**Issue by NKV-obmc** [openbmc/service-config-manager#5]
Is there any redfish commands available for controlling the objects created by the service-config-manager?

**Comment by edineshkumar** [comment]
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/network_protocol.hpp#L302

**Comment by NKV-obmc** [comment]
Hi Dinesh Kumar,

Thanks for the reply.
we need an update on our redfish library.

Regards
Nikhil
