### ISSUE TITLE
D-Bus object path is not created for dropbear-SSH

### ISSUE THREAD

**Issue by AswathSrinivasan** [openbmc/service-config-manager#8]
I have added srvcfg-manager recipe in evb-ast2600 and I have corresponding dropbear-SSH service. As instructed in the below link https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Control/Service/README.md
bmcweb and phosphor-ipmi-net recipes are added in my build to create dbus paths for enabling/disabling SSH.

but dbus object path is not created.

output:
![Screenshot from 2023-11-23 16-30-04](https://github.com/openbmc/service-config-manager/assets/54673577/8f584227-7334-4756-a339-5ad21d5e2c0f)

**Comment by geissonator** [comment]
Does this show anything interesting?
```
systemctl status srvcfg-manager.service
```

Is there anything in this file on your system?
```
cat /etc/srvcfg-mgr.json
```

If nothing interesting, try restarting your service and see if that helps:
```
systemctl restart  srvcfg-manager.service
```

**Comment by AswathSrinivasan** [comment]
> Does this show anything interesting?
> 
> ```
> systemctl status srvcfg-manager.service
> ```

This service is enabled and its status is active. I have restarted the service, there is no changes in dbus path.

And /etc/srvcfg-mgr.json is missing.

**Comment by geissonator** [comment]
I think in the end you're trying to do things with evb-ast2600 that none of us have tested (or support). If you don't require it then I'd recommend using our QEMU CI machine (romulus). https://github.com/openbmc/docs/blob/master/development/dev-environment.md has the details on how to boot it up.

I did a quick test by adding servcfg-manager and building it and verified everything looked fine when I booted up:

```
diff --git a/meta-ibm/meta-romulus/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend b/meta-ibm/meta-romulus/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend
index f1b7903cce..81bba43b77 100644
--- a/meta-ibm/meta-romulus/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend
+++ b/meta-ibm/meta-romulus/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend
@@ -1,2 +1,3 @@
 RDEPENDS:${PN}-inventory:append:romulus = " openpower-occ-control id-button"
 RDEPENDS:${PN}-extras:append:romulus = " phosphor-image-signing"
+RDEPENDS:${PN}-extras:append:romulus = " srvcfg-manager"
```

```
root@romulus:~# busctl tree xyz.openbmc_project.Control.Service.Manager
`- /xyz
  `- /xyz/openbmc_project
    `- /xyz/openbmc_project/control
      `- /xyz/openbmc_project/control/service
        |- /xyz/openbmc_project/control/service/_6fbmc_2dconsole_2dssh
        |- /xyz/openbmc_project/control/service/_6fbmc_2dconsole_40ttyS0
        |- /xyz/openbmc_project/control/service/_6fbmc_2dconsole_40ttyVUART0
        |- /xyz/openbmc_project/control/service/_70hosphor_2dipmi_2dnet_40eth0
        |- /xyz/openbmc_project/control/service/_73tart_2dipkvm
        |- /xyz/openbmc_project/control/service/bmcweb
        `- /xyz/openbmc_project/control/service/dropbear
root@romulus:~#
```

**Comment by AswathSrinivasan** [comment]
> Is there anything in this file on your system?
> 
```
> cat /etc/srvcfg-mgr.json
> ```
> 

Did you add this json file for romulus build ?

**Comment by justin0309** [comment]
hi, @geissonator I also have the same problem on aspeed-2500, #4 Is this solution correct?

**Comment by geissonator** [comment]
> hi, @geissonator I also have the same problem on aspeed-2500, https://github.com/openbmc/service-config-manager/issues/4 Is this solution correct?

Yeah, I bet what was found in that issue is what's happening with the evb-ast2600 model. The BMC is not starting all of the OpenBMC services due to a hung service (which is probably due to missing simulated hardware). That holds up the services that the config manager looks at. You either need to dig in and figure out what services are getting hung up and fix them (or the QEMU model) or just use a supported model like romulus for QEMU work.

**Comment by Govindharajen** [comment]
> hi, @geissonator I also have the same problem on aspeed-2500, #4 Is this solution correct?

hi @justin0309 , Did you find any solution regarding this issue? I'm also facing this issue in the evb-ast2600 machine..

**Comment by Govindharajen** [comment]
> Does this show anything interesting?
> 
> ```
> systemctl status srvcfg-manager.service
> ```
> 
> Is there anything in this file on your system?
> 
> ```
> cat /etc/srvcfg-mgr.json
> ```
> 
> If nothing interesting, try restarting your service and see if that helps:
> 
> ```
> systemctl restart  srvcfg-manager.service
> ```

I couldn't have srvcfg-mgr.json file in the /etc. It is important for the creation of object path @geissonator

**Comment by justin0309** [comment]
> > hi, @geissonator I also have the same problem on aspeed-2500, #4 Is this solution correct?
> 
> hi @justin0309 , Did you find any solution regarding this issue? I'm also facing this issue in the evb-ast2600 machine..

solved
1. Confirm that there is a package with srvcfg-manager added
2. Confirm after booting
systemctl list-jobs
No jobs running.

The relevant interface will appear on d-bus.

**Comment by Govindharajen** [comment]
> > > hi, @geissonator I also have the same problem on aspeed-2500, #4 Is this solution correct?
> > 
> > 
> > hi @justin0309 , Did you find any solution regarding this issue? I'm also facing this issue in the evb-ast2600 machine..
> 
> solved
> 
>     1. Confirm that there is a package with srvcfg-manager added
> 
>     2. Confirm after booting
>        systemctl list-jobs
>        No jobs running.
> 
> 
> The relevant interface will appear on d-bus.

Yaah... Its working... Thanks

**Comment by AswathSrinivasan** [comment]
@geissonator I also created the dbus paths by stopping the running jobs in systemctl. And I have doubt. Why we should stop or clear the running jobs in systemctl or is it a bug ?

**Comment by williamspatrick** [comment]
It is a bug with whatever service didn't complete on its own.
